### ISSUE TITLE
ERROR: Could not resolve "react/jsx-dev-runtime"

### ISSUE THREAD

**Issue by theodufort** [souporserious/mdx-to-md#6]
[ERROR] Could not resolve "react/jsx-dev-runtime"

    _mdx_bundler_entry_point-038a9fb5-ba3e-4ce1-96d1-cb203a5f4974.mdx:2:55:
      2 │ import {Fragment as _Fragment, jsxDEV as _jsxDEV} from "react/jsx-dev-runtime";
        ╵                                                        ~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "react/jsx-dev-runtime" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle.

/home/theod/.nvm/versions/node/v18.19.0/lib/node_modules/mdx-to-md/node_modules/esbuild/lib/main.js:1472
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
_mdx_bundler_entry_point-038a9fb5-ba3e-4ce1-96d1-cb203a5f4974.mdx:2:55: ERROR: Could not resolve "react/jsx-dev-runtime"
    at failureErrorWithLog (/home/theod/.nvm/versions/node/v18.19.0/lib/node_modules/mdx-to-md/node_modules/esbuild/lib/main.js:1472:15)
    at /home/theod/.nvm/versions/node/v18.19.0/lib/node_modules/mdx-to-md/node_modules/esbuild/lib/main.js:945:25
    at runOnEndCallbacks (/home/theod/.nvm/versions/node/v18.19.0/lib/node_modules/mdx-to-md/node_modules/esbuild/lib/main.js:1315:45)
    at buildResponseToResult (/home/theod/.nvm/versions/node/v18.19.0/lib/node_modules/mdx-to-md/node_modules/esbuild/lib/main.js:943:7)
    at /home/theod/.nvm/versions/node/v18.19.0/lib/node_modules/mdx-to-md/node_modules/esbuild/lib/main.js:970:16
    at responseCallbacks.<computed> (/home/theod/.nvm/versions/node/v18.19.0/lib/node_modules/mdx-to-md/node_modules/esbuild/lib/main.js:622:9)
    at handleIncomingPacket (/home/theod/.nvm/versions/node/v18.19.0/lib/node_modules/mdx-to-md/node_modules/esbuild/lib/main.js:677:12)
    at Socket.readFromStdout (/home/theod/.nvm/versions/node/v18.19.0/lib/node_modules/mdx-to-md/node_modules/esbuild/lib/main.js:600:7)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v18.19.0

**Comment by CBielstein** [comment]
+1 for me. Node v22.4.1. Installed using `npm install -g mdx-to-md`

**Comment by addisonschultz** [comment]
Also running into this

**Comment by souporserious** [comment]
I haven't been able to reproduce, but marking `react` and `react-dom` as external seemed to build fine still so I added that here https://github.com/souporserious/mdx-to-md/commit/072a060cafd3d19de25a14caa7ec6d5bd5117af9. Please open with a reproduction if you are still experiencing it.
